//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("EmployeesManagerModel", "FK_Employee_Client", "Client", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BlueOpexEmployeesManager.Client), "Employee", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BlueOpexEmployeesManager.Employee), true)]
[assembly: EdmRelationshipAttribute("EmployeesManagerModel", "FK_JobTitle_Client", "Client", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BlueOpexEmployeesManager.Client), "JobTitle", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BlueOpexEmployeesManager.JobTitle), true)]
[assembly: EdmRelationshipAttribute("EmployeesManagerModel", "FK_User_Client", "Client", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BlueOpexEmployeesManager.Client), "User", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BlueOpexEmployeesManager.User), true)]
[assembly: EdmRelationshipAttribute("EmployeesManagerModel", "FK_Employee_JobTitle_Employee", "Employee", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BlueOpexEmployeesManager.Employee), "Employee_JobTitle", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BlueOpexEmployeesManager.Employee_JobTitle), true)]
[assembly: EdmRelationshipAttribute("EmployeesManagerModel", "FK_Employee_JobTitle_JobTitle", "JobTitle", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(BlueOpexEmployeesManager.JobTitle), "Employee_JobTitle", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(BlueOpexEmployeesManager.Employee_JobTitle), true)]

#endregion

namespace BlueOpexEmployeesManager
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class EmployeesManagerEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new EmployeesManagerEntities object using the connection string found in the 'EmployeesManagerEntities' section of the application configuration file.
        /// </summary>
        public EmployeesManagerEntities() : base("name=EmployeesManagerEntities", "EmployeesManagerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EmployeesManagerEntities object.
        /// </summary>
        public EmployeesManagerEntities(string connectionString) : base(connectionString, "EmployeesManagerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new EmployeesManagerEntities object.
        /// </summary>
        public EmployeesManagerEntities(EntityConnection connection) : base(connection, "EmployeesManagerEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Client> Client
        {
            get
            {
                if ((_Client == null))
                {
                    _Client = base.CreateObjectSet<Client>("Client");
                }
                return _Client;
            }
        }
        private ObjectSet<Client> _Client;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Employee> Employee
        {
            get
            {
                if ((_Employee == null))
                {
                    _Employee = base.CreateObjectSet<Employee>("Employee");
                }
                return _Employee;
            }
        }
        private ObjectSet<Employee> _Employee;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Employee_JobTitle> Employee_JobTitle
        {
            get
            {
                if ((_Employee_JobTitle == null))
                {
                    _Employee_JobTitle = base.CreateObjectSet<Employee_JobTitle>("Employee_JobTitle");
                }
                return _Employee_JobTitle;
            }
        }
        private ObjectSet<Employee_JobTitle> _Employee_JobTitle;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<JobTitle> JobTitle
        {
            get
            {
                if ((_JobTitle == null))
                {
                    _JobTitle = base.CreateObjectSet<JobTitle>("JobTitle");
                }
                return _JobTitle;
            }
        }
        private ObjectSet<JobTitle> _JobTitle;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> User
        {
            get
            {
                if ((_User == null))
                {
                    _User = base.CreateObjectSet<User>("User");
                }
                return _User;
            }
        }
        private ObjectSet<User> _User;

        #endregion

        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Client EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClient(Client client)
        {
            base.AddObject("Client", client);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Employee EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEmployee(Employee employee)
        {
            base.AddObject("Employee", employee);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Employee_JobTitle EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToEmployee_JobTitle(Employee_JobTitle employee_JobTitle)
        {
            base.AddObject("Employee_JobTitle", employee_JobTitle);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the JobTitle EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToJobTitle(JobTitle jobTitle)
        {
            base.AddObject("JobTitle", jobTitle);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the User EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUser(User user)
        {
            base.AddObject("User", user);
        }

        #endregion

    }

    #endregion

    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EmployeesManagerModel", Name="Client")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Client : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Client object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        public static Client CreateClient(global::System.Int32 id)
        {
            Client client = new Client();
            client.id = id;
            return client;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EmployeesManagerModel", "FK_Employee_Client", "Employee")]
        public EntityCollection<Employee> Employee
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Employee>("EmployeesManagerModel.FK_Employee_Client", "Employee");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Employee>("EmployeesManagerModel.FK_Employee_Client", "Employee", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EmployeesManagerModel", "FK_JobTitle_Client", "JobTitle")]
        public EntityCollection<JobTitle> JobTitle
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<JobTitle>("EmployeesManagerModel.FK_JobTitle_Client", "JobTitle");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<JobTitle>("EmployeesManagerModel.FK_JobTitle_Client", "JobTitle", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EmployeesManagerModel", "FK_User_Client", "User")]
        public EntityCollection<User> User
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<User>("EmployeesManagerModel.FK_User_Client", "User");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<User>("EmployeesManagerModel.FK_User_Client", "User", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EmployeesManagerModel", Name="Employee")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Employee : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Employee object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="clientId">Initial value of the clientId property.</param>
        /// <param name="birth">Initial value of the birth property.</param>
        public static Employee CreateEmployee(global::System.Int32 id, global::System.Int32 clientId, global::System.DateTime birth)
        {
            Employee employee = new Employee();
            employee.id = id;
            employee.clientId = clientId;
            employee.birth = birth;
            return employee;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String document_identity
        {
            get
            {
                return _document_identity;
            }
            set
            {
                Ondocument_identityChanging(value);
                ReportPropertyChanging("document_identity");
                _document_identity = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("document_identity");
                Ondocument_identityChanged();
            }
        }
        private global::System.String _document_identity;
        partial void Ondocument_identityChanging(global::System.String value);
        partial void Ondocument_identityChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String document_CPF
        {
            get
            {
                return _document_CPF;
            }
            set
            {
                Ondocument_CPFChanging(value);
                ReportPropertyChanging("document_CPF");
                _document_CPF = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("document_CPF");
                Ondocument_CPFChanged();
            }
        }
        private global::System.String _document_CPF;
        partial void Ondocument_CPFChanging(global::System.String value);
        partial void Ondocument_CPFChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String document_passport
        {
            get
            {
                return _document_passport;
            }
            set
            {
                Ondocument_passportChanging(value);
                ReportPropertyChanging("document_passport");
                _document_passport = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("document_passport");
                Ondocument_passportChanged();
            }
        }
        private global::System.String _document_passport;
        partial void Ondocument_passportChanging(global::System.String value);
        partial void Ondocument_passportChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String comments
        {
            get
            {
                return _comments;
            }
            set
            {
                OncommentsChanging(value);
                ReportPropertyChanging("comments");
                _comments = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("comments");
                OncommentsChanged();
            }
        }
        private global::System.String _comments;
        partial void OncommentsChanging(global::System.String value);
        partial void OncommentsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 clientId
        {
            get
            {
                return _clientId;
            }
            set
            {
                OnclientIdChanging(value);
                ReportPropertyChanging("clientId");
                _clientId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("clientId");
                OnclientIdChanged();
            }
        }
        private global::System.Int32 _clientId;
        partial void OnclientIdChanging(global::System.Int32 value);
        partial void OnclientIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime birth
        {
            get
            {
                return _birth;
            }
            set
            {
                OnbirthChanging(value);
                ReportPropertyChanging("birth");
                _birth = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("birth");
                OnbirthChanged();
            }
        }
        private global::System.DateTime _birth;
        partial void OnbirthChanging(global::System.DateTime value);
        partial void OnbirthChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EmployeesManagerModel", "FK_Employee_Client", "Client")]
        public Client Client
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Client>("EmployeesManagerModel.FK_Employee_Client", "Client").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Client>("EmployeesManagerModel.FK_Employee_Client", "Client").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Client> ClientReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Client>("EmployeesManagerModel.FK_Employee_Client", "Client");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Client>("EmployeesManagerModel.FK_Employee_Client", "Client", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EmployeesManagerModel", "FK_Employee_JobTitle_Employee", "Employee_JobTitle")]
        public EntityCollection<Employee_JobTitle> Employee_JobTitle
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Employee_JobTitle>("EmployeesManagerModel.FK_Employee_JobTitle_Employee", "Employee_JobTitle");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Employee_JobTitle>("EmployeesManagerModel.FK_Employee_JobTitle_Employee", "Employee_JobTitle", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EmployeesManagerModel", Name="Employee_JobTitle")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Employee_JobTitle : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Employee_JobTitle object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="employeeId">Initial value of the employeeId property.</param>
        /// <param name="jobTitleId">Initial value of the jobTitleId property.</param>
        /// <param name="dateBegin">Initial value of the dateBegin property.</param>
        public static Employee_JobTitle CreateEmployee_JobTitle(global::System.Int32 id, global::System.Int32 employeeId, global::System.Int32 jobTitleId, global::System.DateTime dateBegin)
        {
            Employee_JobTitle employee_JobTitle = new Employee_JobTitle();
            employee_JobTitle.id = id;
            employee_JobTitle.employeeId = employeeId;
            employee_JobTitle.jobTitleId = jobTitleId;
            employee_JobTitle.dateBegin = dateBegin;
            return employee_JobTitle;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 employeeId
        {
            get
            {
                return _employeeId;
            }
            set
            {
                OnemployeeIdChanging(value);
                ReportPropertyChanging("employeeId");
                _employeeId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("employeeId");
                OnemployeeIdChanged();
            }
        }
        private global::System.Int32 _employeeId;
        partial void OnemployeeIdChanging(global::System.Int32 value);
        partial void OnemployeeIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 jobTitleId
        {
            get
            {
                return _jobTitleId;
            }
            set
            {
                OnjobTitleIdChanging(value);
                ReportPropertyChanging("jobTitleId");
                _jobTitleId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("jobTitleId");
                OnjobTitleIdChanged();
            }
        }
        private global::System.Int32 _jobTitleId;
        partial void OnjobTitleIdChanging(global::System.Int32 value);
        partial void OnjobTitleIdChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime dateBegin
        {
            get
            {
                return _dateBegin;
            }
            set
            {
                OndateBeginChanging(value);
                ReportPropertyChanging("dateBegin");
                _dateBegin = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dateBegin");
                OndateBeginChanged();
            }
        }
        private global::System.DateTime _dateBegin;
        partial void OndateBeginChanging(global::System.DateTime value);
        partial void OndateBeginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> dateEnd
        {
            get
            {
                return _dateEnd;
            }
            set
            {
                OndateEndChanging(value);
                ReportPropertyChanging("dateEnd");
                _dateEnd = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("dateEnd");
                OndateEndChanged();
            }
        }
        private Nullable<global::System.DateTime> _dateEnd;
        partial void OndateEndChanging(Nullable<global::System.DateTime> value);
        partial void OndateEndChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EmployeesManagerModel", "FK_Employee_JobTitle_Employee", "Employee")]
        public Employee Employee
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("EmployeesManagerModel.FK_Employee_JobTitle_Employee", "Employee").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("EmployeesManagerModel.FK_Employee_JobTitle_Employee", "Employee").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Employee> EmployeeReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Employee>("EmployeesManagerModel.FK_Employee_JobTitle_Employee", "Employee");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Employee>("EmployeesManagerModel.FK_Employee_JobTitle_Employee", "Employee", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EmployeesManagerModel", "FK_Employee_JobTitle_JobTitle", "JobTitle")]
        public JobTitle JobTitle
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<JobTitle>("EmployeesManagerModel.FK_Employee_JobTitle_JobTitle", "JobTitle").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<JobTitle>("EmployeesManagerModel.FK_Employee_JobTitle_JobTitle", "JobTitle").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<JobTitle> JobTitleReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<JobTitle>("EmployeesManagerModel.FK_Employee_JobTitle_JobTitle", "JobTitle");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<JobTitle>("EmployeesManagerModel.FK_Employee_JobTitle_JobTitle", "JobTitle", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EmployeesManagerModel", Name="JobTitle")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class JobTitle : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new JobTitle object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="clientId">Initial value of the clientId property.</param>
        public static JobTitle CreateJobTitle(global::System.Int32 id, global::System.Int32 clientId)
        {
            JobTitle jobTitle = new JobTitle();
            jobTitle.id = id;
            jobTitle.clientId = clientId;
            return jobTitle;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 clientId
        {
            get
            {
                return _clientId;
            }
            set
            {
                OnclientIdChanging(value);
                ReportPropertyChanging("clientId");
                _clientId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("clientId");
                OnclientIdChanged();
            }
        }
        private global::System.Int32 _clientId;
        partial void OnclientIdChanging(global::System.Int32 value);
        partial void OnclientIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EmployeesManagerModel", "FK_JobTitle_Client", "Client")]
        public Client Client
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Client>("EmployeesManagerModel.FK_JobTitle_Client", "Client").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Client>("EmployeesManagerModel.FK_JobTitle_Client", "Client").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Client> ClientReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Client>("EmployeesManagerModel.FK_JobTitle_Client", "Client");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Client>("EmployeesManagerModel.FK_JobTitle_Client", "Client", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EmployeesManagerModel", "FK_Employee_JobTitle_JobTitle", "Employee_JobTitle")]
        public EntityCollection<Employee_JobTitle> Employee_JobTitle
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Employee_JobTitle>("EmployeesManagerModel.FK_Employee_JobTitle_JobTitle", "Employee_JobTitle");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Employee_JobTitle>("EmployeesManagerModel.FK_Employee_JobTitle_JobTitle", "Employee_JobTitle", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EmployeesManagerModel", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagrams object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion

    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="EmployeesManagerModel", Name="User")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class User : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new User object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="clientId">Initial value of the clientId property.</param>
        public static User CreateUser(global::System.Int32 id, global::System.Int32 clientId)
        {
            User user = new User();
            user.id = id;
            user.clientId = clientId;
            return user;
        }

        #endregion

        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String login
        {
            get
            {
                return _login;
            }
            set
            {
                OnloginChanging(value);
                ReportPropertyChanging("login");
                _login = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("login");
                OnloginChanged();
            }
        }
        private global::System.String _login;
        partial void OnloginChanging(global::System.String value);
        partial void OnloginChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String passwordHash
        {
            get
            {
                return _passwordHash;
            }
            set
            {
                OnpasswordHashChanging(value);
                ReportPropertyChanging("passwordHash");
                _passwordHash = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("passwordHash");
                OnpasswordHashChanged();
            }
        }
        private global::System.String _passwordHash;
        partial void OnpasswordHashChanging(global::System.String value);
        partial void OnpasswordHashChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String passwordSalt
        {
            get
            {
                return _passwordSalt;
            }
            set
            {
                OnpasswordSaltChanging(value);
                ReportPropertyChanging("passwordSalt");
                _passwordSalt = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("passwordSalt");
                OnpasswordSaltChanged();
            }
        }
        private global::System.String _passwordSalt;
        partial void OnpasswordSaltChanging(global::System.String value);
        partial void OnpasswordSaltChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 clientId
        {
            get
            {
                return _clientId;
            }
            set
            {
                OnclientIdChanging(value);
                ReportPropertyChanging("clientId");
                _clientId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("clientId");
                OnclientIdChanged();
            }
        }
        private global::System.Int32 _clientId;
        partial void OnclientIdChanging(global::System.Int32 value);
        partial void OnclientIdChanged();

        #endregion

    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("EmployeesManagerModel", "FK_User_Client", "Client")]
        public Client Client
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Client>("EmployeesManagerModel.FK_User_Client", "Client").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Client>("EmployeesManagerModel.FK_User_Client", "Client").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Client> ClientReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Client>("EmployeesManagerModel.FK_User_Client", "Client");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Client>("EmployeesManagerModel.FK_User_Client", "Client", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
